### ISSUE TITLE
No widget items 

### ISSUE THREAD

**Issue by phil65** [Ignoble61/service.smartish.widgets#1]
Unfortunaly still doesnt work for me.
The log error msg I mentioned should be fixed with https://github.com/phil65/service.smartish.widgets/commit/f74e7ccc3fe47dbb28baae2f2b114a3b0058b2a8, but that´s not really the issue.
No other useful info available in log.
Any quick ideas?

**Comment by Ignoble61** [comment]
One quick idea - I think it was Martijn who originally suggested that skins have to enable the widgets, to save the script querying the library, processing the results, building widgets and all that if they weren't going to be displayed, so the home.xml (or other relevant file) needs

`Skin.SetBool(enable.smartish.widgets)`

Without that, the script just collect habits.

**Comment by phil65** [comment]
you´re sure that it is setBool and not setProperty?

**Comment by phil65** [comment]
ok, I see, setBool is fine.

**Comment by phil65** [comment]
yup, works now, sorry for the noise. :)  is that documented in some readme or forum thread?

**Comment by Ignoble61** [comment]
I likely documented it in the original forum thread - long time ago so not 100% sure. I'll add a simple readme.

**Comment by phil65** [comment]
thx.
